/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DnaRouteImport } from './routes/dna'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProsRouteImport } from './routes/pros'
import { Route as SessionRouteImport } from './routes/session'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as LearnTopicRouteImport } from './routes/learn.$topic'
import { Route as ProsIdRouteImport } from './routes/pros.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DnaRoute = DnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsRoute = ProsRouteImport.update({
  id: '/pros',
  path: '/pros',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTopicRoute = LearnTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => LearnRoute,
} as any)
const ProsIdRoute = ProsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/compare': typeof CompareRoute
  '/dna': typeof DnaRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/pros': typeof ProsRouteWithChildren
  '/session': typeof SessionRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/pros/$id': typeof ProsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/compare': typeof CompareRoute
  '/dna': typeof DnaRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/pros': typeof ProsRouteWithChildren
  '/session': typeof SessionRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/pros/$id': typeof ProsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/compare': typeof CompareRoute
  '/dna': typeof DnaRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/pros': typeof ProsRouteWithChildren
  '/session': typeof SessionRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/pros/$id': typeof ProsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/compare'
    | '/dna'
    | '/history'
    | '/learn'
    | '/methodology'
    | '/profile'
    | '/progress'
    | '/pros'
    | '/session'
    | '/analysis/$id'
    | '/learn/$topic'
    | '/pros/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/compare'
    | '/dna'
    | '/history'
    | '/learn'
    | '/methodology'
    | '/profile'
    | '/progress'
    | '/pros'
    | '/session'
    | '/analysis/$id'
    | '/learn/$topic'
    | '/pros/$id'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/compare'
    | '/dna'
    | '/history'
    | '/learn'
    | '/methodology'
    | '/profile'
    | '/progress'
    | '/pros'
    | '/session'
    | '/analysis/$id'
    | '/learn/$topic'
    | '/pros/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CompareRoute: typeof CompareRoute
  DnaRoute: typeof DnaRoute
  HistoryRoute: typeof HistoryRoute
  LearnRoute: typeof LearnRouteWithChildren
  MethodologyRoute: typeof MethodologyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ProsRoute: typeof ProsRouteWithChildren
  SessionRoute: typeof SessionRoute
  AnalysisIdRoute: typeof AnalysisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dna': {
      id: '/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof DnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros': {
      id: '/pros'
      path: '/pros'
      fullPath: '/pros'
      preLoaderRoute: typeof ProsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$topic': {
      id: '/learn/$topic'
      path: '/$topic'
      fullPath: '/learn/$topic'
      preLoaderRoute: typeof LearnTopicRouteImport
      parentRoute: typeof LearnRoute
    }
    '/pros/$id': {
      id: '/pros/$id'
      path: '/$id'
      fullPath: '/pros/$id'
      preLoaderRoute: typeof ProsIdRouteImport
      parentRoute: typeof ProsRoute
    }
  }
}

interface LearnRouteChildren {
  LearnTopicRoute: typeof LearnTopicRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnTopicRoute: LearnTopicRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface ProsRouteChildren {
  ProsIdRoute: typeof ProsIdRoute
}

const ProsRouteChildren: ProsRouteChildren = {
  ProsIdRoute: ProsIdRoute,
}

const ProsRouteWithChildren = ProsRoute._addFileChildren(ProsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  CompareRoute: CompareRoute,
  DnaRoute: DnaRoute,
  HistoryRoute: HistoryRoute,
  LearnRoute: LearnRouteWithChildren,
  MethodologyRoute: MethodologyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ProsRoute: ProsRouteWithChildren,
  SessionRoute: SessionRoute,
  AnalysisIdRoute: AnalysisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
